/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Javier.Herrera (https://sketchfab.com/Javier.Herrera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dice-20-c2ca972ad18045fd85849414d24c5813
Title: Dice 20
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three'

import d20Scene from '../assets/3d/dice_20.glb'

const D20Dice = (props) => {
    const d20Ref = useRef();
  const { nodes, materials } = useGLTF(d20Scene);
  return (
    <a.group ref={d20Ref} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.128}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.LowPoli}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </a.group>
  );
}

export default D20Dice;
